BuffteksWebsite/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BuffteksWebsite.Models
{
    public class Project
    {
        [Key]
        public string ID {get; set;}
        [Display(Name = "Project Name")]
        public string ProjectName { get; set; }
        [Display(Name = "Project Description")] 
        public string Details {get; set;}
        public ICollection<ProjectRoster> Participants { get; set; }
        public override string ToString(){
            return $"Project Name: {this.ProjectName}\nProject Description: {this.Details}";
        }
    }
}

BuffteksWebsite/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BuffteksWebsite.Models;

namespace BuffteksWebsite.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly BuffteksWebsiteContext _context;

        public ProjectsController(BuffteksWebsiteContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Projects.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .SingleOrDefaultAsync(m => m.ID == id);

            if (project == null)
            {
                return NotFound();
            }

            var clients = 
                from participant in _context.Clients
                join projectparticipant in _context.ProjectRoster
                on participant.ID equals projectparticipant.ProjectParticipantID
                where project.ID == projectparticipant.ProjectID
                select participant;

            var members = 
                from participant in _context.Members
                join projectparticipant in _context.ProjectRoster
                on participant.ID equals projectparticipant.ProjectParticipantID
                where project.ID == projectparticipant.ProjectID                
                select participant;

            ProjectDetailViewModel pdvm = new ProjectDetailViewModel
            {
                TheProject = project,
                ProjectClients = clients.ToList() ?? null,
                ProjectMembers = members.ToList() ?? null
            };


            return View(pdvm);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ProjectName,Details")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.SingleOrDefaultAsync(m => m.ID == id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,ProjectName,Details")] Project project)
        {
            if (id != project.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/EditProjectParticipants/5
        public async Task<IActionResult> EditProjectParticipants(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.SingleOrDefaultAsync(m => m.ID == id);
            if (project == null)
            {
                return NotFound();
            }


            //var clients = await _context.Clients.ToListAsync();

            //CLIENTS
            //pull 'em into lists first
            var clients = await _context.Clients.ToListAsync();
            var projectroster = await _context.ProjectRoster.ToListAsync();

            /*
            var uniqueclients = 
                from participant in clients
                join projectparticipant in projectroster
                on participant.ID equals projectparticipant.ProjectParticipantID
                where participant.ID != projectparticipant.ProjectParticipantID
                select participant;
            */                

            List<SelectListItem> clientsSelectList = new List<SelectListItem>();

            foreach(var client in clients)
            {
                clientsSelectList.Add(new SelectListItem { Value=client.ID, Text = client.FirstName + " " + client.LastName});
            }

            //MEMBERS
            //pull 'em into lists first
            var members = await _context.Members.ToListAsync();

            /*
            var uniquemembers = 
                from participant in members
                join projectparticipant in projectroster
                on participant.ID equals projectparticipant.ProjectParticipantID
                where participant.ID != projectparticipant.ProjectParticipantID
                select participant;    
            */                

            List<SelectListItem> membersSelectList = new List<SelectListItem>();
            var membersforedit = 
                from participant in _context.Members
                join projectparticipant in _context.ProjectRoster
                on participant.ID equals projectparticipant.ProjectParticipantID
                where project.ID == projectparticipant.ProjectID
                select participant;
            int indx = -1;

            foreach(var member in members)
            {
                indx++;
                membersSelectList.Add(new SelectListItem { Value=member.ID, Text = member.FirstName + " " + member.LastName});
                foreach(var item in membersforedit){
                    if(membersSelectList.Any(d => d.Value == item.ID)){
                        membersSelectList.RemoveAt(indx);
                        indx--;
                    }
                }

            }
            
            var clientsforedit = 
                from participant in _context.Clients
                join projectparticipant in _context.ProjectRoster
                on participant.ID equals projectparticipant.ProjectParticipantID
                where project.ID == projectparticipant.ProjectID
                select participant;


            
            //foreach(var item in membersforedit){
            //    foreach(var item2 in membersSelectList){
            //        if(item2.Value == item.ID){
            //            membersSelectListToSend.Remove(item2);
            //        }
            //    }
            //}
            //create and prepare ViewModel
            EditProjectDetailViewModel epdvm = new EditProjectDetailViewModel
            {
                TheProject = project,
                ProjectClients = clientsforedit.ToList() ?? null,
                //ProjectMembers = membersforedit.ToList() ?? null,
                ProjectClientsList = clientsSelectList,
                ProjectMembersList = membersSelectList
            };
            

            return View(epdvm);
        }        
        [HttpPost]
        public async Task<IActionResult> EditProjectParticipants(String id, EditProjectDetailViewModel model){
            var membersFromDb = _context.Members.ToList();
            Member ans = null;
            foreach(var items in membersFromDb){
                if(items.ID == model.SelectedID){
                    ans = items;
                }
            }
            var projectroster = new ProjectRoster {
                    ProjectID = model.TheProject.ID.ToString(), 
                    Project = model.TheProject,
                    ProjectParticipantID = model.SelectedID.ToString(),
                    ProjectParticipant = ans};
            _context.ProjectRoster.Add(projectroster);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .SingleOrDefaultAsync(m => m.ID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var project = await _context.Projects.SingleOrDefaultAsync(m => m.ID == id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

BuffteksWebsite/Views/Projects/Create.cshtml
@model BuffteksWebsite.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BuffteksWebsite/Views/Projects/Delete.cshtml
@model BuffteksWebsite.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BuffteksWebsite/Views/Projects/Details.cshtml
@model BuffteksWebsite.Models.ProjectDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TheProject.ProjectName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TheProject.ProjectName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TheProject.Details)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TheProject.Details)
        </dd>
    </dl>
</div>
<div>
    <h4>
        Participants - Client
    </h4>
    <hr />    
    <table class="table">
        <thead>
            <tr>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var client in Model.ProjectClients) {
            <tr>
                <td>
                    @Html.DisplayFor(c => client.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(c => client.LastName)
                </td>
            </tr>
    }
        </tbody>
    </table>    
</div>
<div>
    <h4>
        Participants - Member
    </h4>
    <hr />    
    <table class="table">
        <thead>
            <tr>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var member in Model.ProjectMembers) {
            <tr>
                <td>
                    @Html.DisplayFor(m => member.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(m => member.LastName)
                </td>
            </tr>
    }
        </tbody>
    </table>    
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TheProject.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BuffteksWebsite/Views/Projects/Edit.cshtml
@model BuffteksWebsite.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BuffteksWebsite/Views/Projects/EditProjectParticipants.cshtml
@model BuffteksWebsite.Models.EditProjectDetailViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Project Particpants - Add Participants to Project: @Model.TheProject.ProjectName</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @*        
        <form asp-action="EditProjectParticipants">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectDescription" class="control-label"></label>
                <input asp-for="ProjectDescription" class="form-control" />
                <span asp-validation-for="ProjectDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
        *@
        @if(Model.ProjectClients.Count < 1 ){
        <form asp-controller="Projects" asp-action="EditProjectParticipants" method="post">
            <div class="form-group">
                <label asp-for="SelectedID" class="control-label">Select from Clients</label>
                <select asp-for="SelectedID" asp-items="Model.ProjectClientsList"></select> 
            </div>
            <div class="form-group">
                <input type="submit" value="Select New Client for Project" class="btn btn-default" />
            </div>
        </form>
        }
        <form asp-controller="Projects" asp-action="EditProjectParticipants" method="post">
            <div class="form-group">
                <label asp-for="SelectedID" class="control-label">Select from Members</label>
                <select asp-for="SelectedID" asp-items="Model.ProjectMembersList"></select> 
            </div>
            <div class="form-group">
                <input type="submit" value="Select New Member for Project" class="btn btn-default" />
            </div>
        </form>        
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BuffteksWebsite/Views/Projects/Index.cshtml
@model IEnumerable<BuffteksWebsite.Models.Project>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProjectName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Details)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a> |
                <a asp-action="EditProjectParticipants" asp-route-id="@item.ID">Add or Remove Participants</a>
            </td>
        </tr>
}
    </tbody>
</table>